site_name: netplotbrain

nav:
    - Home:
        ../README.md
    - Tutorial: 
        tutorial.md
    - Gallary: gallary.md

theme: readthedocs

plugins:
    - search
    - mktheapidocs:
        modules:
            netplotbrain:
                section: API
                source_repo: ./netplotbrain/plot.py
                hidden: ["utils"]

