site_name: netplotbrain

nav:
    - Home: index.md
    - Tutorial: 
        tutorial.md
    - Gallary: gallary.md

theme: readthedocs

plugins:
    - search
    - mktheapidocs:
        modules: 
            netplotbrain:
                section: API 
                hidden: ["utils"]

