site_name: netplotbrain

nav:
    - Home: index.md
    - Tutorial: 
        tutorial.md
    - Gallary: gallary.md

theme: readthedocs

plugins:
    - include-markdown
    - search
    - mktheapidocs:
        modules: 
            netplotbrain:
                section: API 
                source_repo: github.com/wiheto/netplotbrain/
                hidden: ["utils"]

