site_name: netplotbrain

theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: purple
plugins:
    - search
    - pheasant
    - awesome-pages
    - mkdocstrings:
        default_handler: python
        handlers:
        python:
            rendering:
                show_source: true
        watch:
            - netplotbrian/