site_name: netplotbrain

nav:
    - Home: index.md
    - Tutorial: tutorial.md
    - API: api.md
    - gallery: gallery.md

theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: purple

plugins:
    - search
    - awesome-pages
    - mkdocs-jupyter:
        execute: True
        allow_errors: false
        ignore_h1_titles: True
    - mkdocstrings:
        default_handler: python
        handlers:
        python:
            rendering:
                show_source: true
        watch:
            - netplotbrian/
