site_name: netplotbrain

nav:
    - Tutorial: 
        tutorial.md
    - Gallary: gallary.md
    - API:
        api.md

theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: purple

plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
        python:
            rendering:
                show_source: true
        watch:
            - netplotbrian/
